title: "First Steps to Quarto"
subtitle: "Some examples"
author: "Max Fordham"
date: 2023-10-16
format:
  pdf:
    documentclass: scrreprt
    include-in-header:
      - preamble.tex
    template-partials:
      - before-body.tex
      - toc.tex
      - tables.tex